version: 2.1

orbs:
    ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          BUNDLER_VERSION: 1.17.2
    steps:
      - checkout
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 1.17.2
      - image: circleci/mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DB: fes_app_test

    steps:
      - checkout
      - ruby/install-deps
      - run: mv config/database.ci.yml config/database.yml
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack

      - run:
          name: テストの実行
          command: bundle exec rspec

  # deploy:
  #   docker:
  #     - image: circleci/ruby:2.6.6-node-browsers
  #       environment:
  #         BUNDLER_VERSION: 1.17.2
  #   steps:
  #     - checkout
  #     - ruby/install-deps
  #     - add_ssh_keys:
  #         fingerprints: "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"
  #     - deploy:
  #         name: Capistrano deploy
  #         command: bundle exec cap production deploy


workflows:
  version: 2
  workflows:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
